name: "Build DEB Package"
description: "Builds a DEB package using a Docker image"

inputs:
  ice_version:
    description: "The Ice version to build"
    required: false
  repository_url:
    description: "The URL of the DEB repository to publish to"
    required: false
  repository_suffix:
    description: "The suffix to append to the repository URL"
    required: false
  deb_build_options:
    description: "DEB_BUILD_OPTIONS for the build"
    required: false
  deb_build_profiles:
    description: "DEB_BUILD_PROFILES for the build"
    required: false
  distribution:
    description: "The target distribution: (e.g., ubuntu-24.04, debian-12)"
    required: true
  arch:
    description: "The target build architecture: (e.g., x86_64, aarch64)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Docker Image
      run: docker build --pull -f "ice/packaging/dpkg/docker/${{ inputs.distribution }}/Dockerfile" -t ice-deb-package-builder "$GITHUB_WORKSPACE/ice"
      shell: bash

    - name: Build DEB Packages
      run: |
        docker run --rm \
          -v "$GITHUB_WORKSPACE:/workspace" \
          -e DEBEMAIL="ci@zeroc.com" \
          -e DEBFULLNAME="CI" \
          -e ICE_VERSION=${{ inputs.ice_version }} \
          -e DEB_BUILD_OPTIONS="${{ inputs.deb_build_options }}" \
          -e DEB_BUILD_PROFILES="${{ inputs.deb_build_profiles }}" \
          ice-deb-package-builder /workspace/ice/packaging/dpkg/build-package.sh
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-packages-${{ inputs.distribution }}-${{ inputs.arch }}
        path: |
          *.deb
          *.ddeb
          *.dsc
          *.tar.xz
          *.tar.gz
          *.changes
          *.buildinfo

    - name: Publish DEB Packages
      run: |
        docker run --rm \
          -v "$GITHUB_WORKSPACE:/workspace" \
          -e REPOSITORY_URL="${{ inputs.repository_url }}/${{ inputs.distribution }}${{ inputs.repository_suffix }}/" \
          -e REPOSITORY_USERNAME="$REPOSITORY_USERNAME" \
          -e REPOSITORY_PASSWORD="$REPOSITORY_PASSWORD" \
          ice-deb-package-builder /workspace/ice/packaging/dpkg/publish-packages.sh
      shell: bash
      if: inputs.repository_url != ''
