# Copyright (c) ZeroC, Inc.

# Define debug as true if you want to build with debug information, false otherwise.
debug = true

# Windows specific options

# The platform uses by the C++ builds, supported values are `x64` and `Win32`, that is required to locate the
# slice2java compiler in the platform depend directory.
cppPlatform =

# The configuration uses by the C++ builds, supported values are `Debug` and `Release`, that is required to locate the
# slice2java compiler in the configuration depend directory.
cppConfiguration =

# Gradle build properties

org.gradle.parallel = true

# More heap!
org.gradle.jvmargs = -Xmx1024m

# Enable gradle configuration cache
org.gradle.configuration-cache=true
