name: "Build RPM Package"
description: "Builds a RPM package using a Docker image"
inputs:
  ice_version:
    description: "The Ice version to build"
    required: true
  os:
    description: "The target OS (e.g., ubuntu-24.04, ubuntu-24.04-arm)"
    required: true
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Docker Image
      run: docker build --pull -f ${{ inputs.dockerfile_path }} -t ice-rpm-package-builder .
      shell: bash

    - name: Run Package Build with Mounted Source
      run: |
        docker run --rm \
          -v "$GITHUB_WORKSPACE:/workspace" \
          -e ICE_VERSION=${{ inputs.ice_version }} \
          ice-rpm-package-builder /workspace/ice/packaging/rpm/build-package.sh
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rpm-packages-${{ inputs.os }}
        path: *.rpm
