name: "Build Brew Packages"

on:
  workflow_call:
    inputs:
      ice_version:
        required: true
        type: string
      repository_url:
        required: false
        type: string
      repository_username:
        required: false
        type: string
    secrets:
      REPOSITORY_PASSWORD:
        required: false
      ICE_NIGHTLY_PUBLISH_TOKEN:
        required: false
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version number to use"
        required: true
      repository_url:
        description: "The URL of the repository to publish to"
        required: false
        type: string
      repository_username:
        description: "The username to authenticate with the repository"
        required: false
        type: string

permissions:
  contents: write

jobs:
  build-brew-packages:
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup C++
        uses: ./.github/actions/setup-cpp

      - name: Setup Cache
        uses: ./.github/actions/setup-cache
        with:
          prefix: build-brew-packages

      - name: Update Nightly Tap
        run: ./packaging/brew/update-nightly-tap.sh "${{ inputs.ice_version }}" "${{ inputs.repository_url }}/nightly"

      - name: Upload Nightly Bottle
        run: |
          curl -u "${{ inputs.repository_username }}:${{ secrets.REPOSITORY_PASSWORD }}" \
            --ftp-create-dirs \
            --upload-file ice-*.bottle.*tar.gz \
            --output /dev/null \
            --silent \
            --retry 3 \
            --fail \
            --show-error \
            ${{ inputs.repository_url }}/nightly/ || { echo "Upload failed"; exit 1; }

      - name: Push Nightly Tap
        run: |
          cd "$(brew --repo zeroc-ice/nightly)"
          git remote set-url origin "https://x-access-token:${{secrets.ICE_NIGHTLY_PUBLISH_TOKEN}}@github.com/zeroc-ice/homebrew-nightly.git"
          git push origin main || { echo "Push failed"; exit 1; }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: homebrew-bottle
          path: ./*.bottle.tar.gz
