// Copyright (c) ZeroC, Inc.

// slice2js version 3.9.0-alpha.0
// <auto-generated>Generated from Slice file 'FirstDeep.ice'.</auto-generated>

import * as __module__zeroc_ice from "@zeroc/ice";

export namespace Outer {
    namespace Inner {
        namespace Transitive {
            /**
             *
             * @remarks
             * The Slice compiler generated this class from Slice struct `::Outer::Inner::Transitive::TransitiveFirst`.
             */
            export class TransitiveFirst {
                constructor(transitiveValue?: number);

                /**
                 * A deep copy of the current object.
                 *
                 * @returns A deep copy of the current object.
                 */
                clone(): TransitiveFirst;

                /**
                 * Determines whether the specified object is equal to the current object.
                 *
                 * @param other The object to compare with the current object.
                 * @returns `true` if the specified object is equal to the current object, `false` otherwise.
                 */
                equals(other: any): boolean;

                /**
                 * Returns the hash code of the object.
                 *
                 * @returns The hash code of the object.
                 */
                hashCode(): number;

                /**
                 * Writes the {@link TransitiveFirst} value to the given OutputStream.
                 *
                 * @param outs The OutputStream to write to.
                 * @param value The value to write.
                 */
                static write(outs: __module__zeroc_ice.Ice.OutputStream, value:TransitiveFirst): void;

                /**
                 * Reads {@link TransitiveFirst} from the given InputStream.
                 *
                 * @param ins The InputStream to read from.
                 * @returns The read {@link TransitiveFirst} value.
                 */
                static read(ins: __module__zeroc_ice.Ice.InputStream): TransitiveFirst;

                transitiveValue: number;
            }
        }
    }
}
