// Copyright (c) ZeroC, Inc.

// slice2js version 3.9.0-alpha.0
// <auto-generated>Generated from Slice file 'FirstDeep.ice'.</auto-generated>

/* eslint-disable */
/* jshint ignore: start */

import { Ice } from "@zeroc/ice";

export const Outer = {};
Outer.Inner = Outer.Inner || {};
Outer.Inner.Transitive = Outer.Inner.Transitive || {};

Outer.Inner.Transitive.TransitiveFirst = class {
    constructor(transitiveValue = 0) {
        this.transitiveValue = transitiveValue;
    }

    _write(ostr) {
        ostr.writeInt(this.transitiveValue);
    }

    _read(istr) {
        this.transitiveValue = istr.readInt();
    }

    static get minWireSize() {
        return  4;
    }
};

Ice.defineStruct(Outer.Inner.Transitive.TransitiveFirst, true, false);
