name: "Build DEB Packages"

on:
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version to build"
        required: true
        default: "3.8.0~alpha0"
      deb_build_options:
        description: "DEB_BUILD_OPTIONS for the build"
        required: false
        default: "nocheck parallel=4"
      repository_url:
        description: "The URL of the Nexus repository to publish to"
        default: "http://localhost:8081/repository/"
        required: false
        type: string
  workflow_call:
    inputs:
      ice_version:
        required: true
        type: string
      deb_build_options:
        type: string
        required: true
      repository_url:
        required: true
        type: string

jobs:
  build:
    name: "Build for ${{ matrix.os }}"
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        include:
          - distribution: ubuntu-24.04
            arch: x86_64

          - distribution: ubuntu-24.04
            arch: aarch64

          - distribution: debian-12
            arch: x86_64
            build_profiles: "no-python312"

          - os: debian12
            arch: aarch64
            build_profiles: "no-python312"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: ice

      - name: Call Build Debian Package Action
        uses: ./ice/.github/actions/build-deb-package
        with:
          ice_version: ${{ inputs.ice_version }}
          deb_build_options: ${{ inputs.deb_build_options || '' }}
          distribution: ${{ matrix.distribution }}
          arch: ${{ matrix.arch }}
          repository_url: ${{ inputs.repository_url }}
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
