name: "Build PIP Packages"

on:
  workflow_call:
    inputs:
      ice_version:
        required: true
        type: string
      repository-url:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version to build"
        required: true
        default: "3.8.0~alpha0"
      repository-url:
        description: "The URL of the PYPI registry to publish to"
        default: "http://localhost:8081/repository/pypi-nightly/"
        required: false
        type: string

jobs:
  build-python-packages:
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Install Build Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build

      - name: Build PIP Package
        working-directory: python
        run: python3 -m build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pip-packages-${{ matrix.os }}
          path: |
            python/dist/zeroc_ice-*.whl
            python/dist/zeroc_ice-*.tar.gz

  pack-dotnet:
    runs-on: ubuntu-latest
    needs: build-python-packages

    steps:
      - name: Download All Compiler Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish PIP Package
        run: mkdir -p ${{ github.workspace }}/dist
          cp -r artifacts/pip-packages-windows-latest/*.whl ${{ github.workspace }}/dist
          cp -r artifacts/pip-packages-macos-latest/*.whl ${{ github.workspace }}/dist
          cp -r artifacts/pip-packages-macos-latest/*.tar.gz ${{ github.workspace }}/dist

          python3 -m pip install --upgrade twine
          python3 -m twine upload --repository-url ${{ inputs.repository-url }} python/dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
