name: "Build MATLAB Packages"

on:
  workflow_call:
    inputs:
      repository_url:
        required: false
        type: string
      repository_username:
        required: false
        type: string
    secrets:
      REPOSITORY_PASSWORD:
        required: false
  workflow_dispatch:
    inputs:
      repository_url:
        description: "The URL of the repository to publish to"
        required: false
        type: string
      repository_username:
        description: "The username to authenticate with the repository"
        required: false
        type: string

jobs:
  build-matlab-packages:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup C++
        uses: ./.github/actions/setup-cpp

      - name: Setup MATLAB
        uses: ./.github/actions/setup-matlab

      - name: Setup Cache
        uses: ./.github/actions/setup-cache
        with:
          prefix: build-matlab-packages

      - name: Build Linux MATLAB ToolBox
        run: |
          make -C cpp srcs
          make -C matlab toolbox
        if: runner.os == 'Linux'

      - name: Build Windows MATLAB ToolBox
        run: MSBuild /p:Configuration=Release /p:Platform=x64 /t:Package matlab\msbuild\ice.proj
        if: runner.os == 'Windows'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: matlab-packages-${{ matrix.os }}
          path: matlab/toolbox/*.mltbx

      - name: Publish MATLAB ToolBox
        shell: bash
        run: |
          curl -u "${REPOSITORY_USERNAME}:${REPOSITORY_PASSWORD}" \
              --upload-file matlab/toolbox/*.mltbx \
              --output /dev/null \
              --silent \
              --retry 3 \
              --fail \
              --show-error \
              ${{ inputs.repository_url }}/ || { echo "Upload failed"; exit 1; }
        if: inputs.repository_url != ''
        env:
          REPOSITORY_USERNAME: ${{ inputs.repository_username }}
          REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
