name: "Build Maven Packages"

on:
  workflow_call:
    inputs:
      ice_version:
        required: false
        type: string
      repository_url:
        required: false
        type: string
      repository_username:
        required: false
        type: string
    secrets:
      MAVEN_PASSWORD:
        required: false
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version to build"
        required: false
      repository_url:
        description: "The URL of the Maven repository to publish to"
        required: false
        type: string
      repository_username:
        description: "The username to authenticate with the repository"
        required: false
        type: string

jobs:
  build-maven-packages:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Build Slice Compiler
        run: make slice2java
        working-directory: cpp

      - name: Update Ice Version
        run: |
          sed -i "s/^iceVersion = .*/iceVersion = ${{ inputs.ice_version }}/" java/gradle.properties
          sed -i "s/^sliceToolsVersion = .*/sliceToolsVersion = ${{ inputs.ice_version }}/" java/tools/slice-tools/gradle.properties
        if: inputs.ice_version != ''

      - name: Build Java Packages
        run: ./gradlew dist
        working-directory: java

      - name: Upload Java Packages
        uses: actions/upload-artifact@v4
        with:
          name: java-packages
          path: java/lib/*

      - name: Publish Maven Packages
        run: ./gradlew publish
        working-directory: java
        env:
          MAVEN_REPOSITORY: ${{ inputs.repository_url }}
          MAVEN_USERNAME: ${{ inputs.repository_username }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        if: inputs.repository_url != ''
