name: "Build RPM Packages"

on:
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version to build"
        required: false
      repository_url:
        description: "The URL of the Nexus repository to publish to"
        required: false
        type: string
      repository_suffix:
        description: "The suffix to append to the repository URL"
        required: false
        type: string
      repository_username:
        description: "The username to authenticate with the repository"
        required: false
        type: string
  workflow_call:
    inputs:
      ice_version:
        required: false
        type: string
      repository_url:
        required: false
        type: string
      repository_suffix:
        required: false
        type: string
      repository_username:
        required: false
        type: string
    secrets:
      REPOSITORY_PASSWORD:
        required: false

jobs:
  build:
    name: "Build for ${{ matrix.distribution }}-${{ matrix.arch }}"
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        include:
          - distribution: rhel9
            arch: x86_64
            image: ghcr.io/zeroc-ice/ice-rpm-package-builder-x86_64-rhel9:latest

          - distribution: rhel9
            arch: aarch64
            image: ghcr.io/zeroc-ice/ice-rpm-package-builder-aarch64-rhel9:latest

          - distribution: rhel10
            arch: x86_64
            image: ghcr.io/zeroc-ice/ice-rpm-package-builder-x86_64-rhel10:latest

          - distribution: rhel10
            arch: aarch64
            image: ghcr.io/zeroc-ice/ice-rpm-package-builder-aarch64-rhel10:latest

          - distribution: amzn2023
            arch: x86_64
            image: ghcr.io/zeroc-ice/ice-rpm-package-builder-x86_64-amzn2023:latest

          - distribution: amzn2023
            arch: aarch64
            image: ghcr.io/zeroc-ice/ice-rpm-package-builder-aarch64-amzn2023:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: ice

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u zeroc-ice --password-stdin

      - name: Build RPM packages
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/workspace" \
            -e ICE_VERSION="${{ inputs.ice_version }}" \
            -e GIT_TAG="${{ github.ref_name }}" \
            ${{ inputs.image }} \
            /workspace/ice/packaging/rpm/build-package.sh

      - name: Sign RPM packages
        run: |
          args=(
            --rm
            -v "$GITHUB_WORKSPACE:/workspace"
            -e GPG_KEY="${{ secrets.GPG_KEY }}"
            -e GPG_KEY_ID="${{ secrets.GPG_KEY_ID }}"
            rpm-repo-builder
          )

          docker run "${args[@]}" /workspace/ice/packaging/rpm/rpm-sign.sh /workspace/build/RPMS
          docker run "${args[@]}" /workspace/ice/packaging/rpm/rpm-sign.sh /workspace/build/SRPMS

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpm-packages-${{ inputs.distribution }}-${{ inputs.arch }}
          path: |
            build/RPMS/*
            build/SRPMS/*
