name: "Build Ice Repo DEB Packages"

on:
  workflow_dispatch

jobs:
  build:
    name: "Build Ice Repo DEB packages for ${{ matrix.distribution }}"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - distribution: debian12
            channel: 3.8

          - distribution: ubuntu24.04
            channel: 3.8

          - distribution: debian12
            channel: nightly

          - distribution: ubuntu24.04
            channel: nightly

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: ice

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: zeroc-ice
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build DEB packages
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/workspace" \
            -e GPG_KEY="${{ secrets.ICE_3_8_CI_SIGNER_KEY }}" \
            -e GPG_KEY_ID="${{ secrets.ICE_3_8_CI_SIGNER_KEY_ID }}" \
            ghcr.io/zeroc-ice/ice-deb-builder-${{ matrix.distribution }} \
            /workspace/ice/packaging/deb/build-repo-package.sh \
            --distribution="${{ matrix.distribution }}" \
            --channel="${{ matrix.channel }}"

      - name: Sync DEB packages to S3
        run: |
          # Validate CHANNEL
          case "$CHANNEL" in
            3.8|nightly) ;;
            *)
              echo "Invalid CHANNEL: $CHANNEL"
              exit 1
              ;;
          esac

          # Validate DISTRIBUTION
          case "$DISTRIBUTION" in
            debian12|ubuntu24.04) ;;
            *)
              echo "Invalid DISTRIBUTION: $DISTRIBUTION"
              exit 1
              ;;
          esac

          mkdir -p "$DISTRIBUTION"
          aws s3 sync s3://zeroc-downloads/ice/$CHANNEL/$DISTRIBUTION $DISTRIBUTION

          cp -pn "build/*.deb" "${DISTRIBUTION}/"

          aws s3 sync "$DISTRIBUTION" s3://zeroc-downloads/ice/$CHANNEL/$DISTRIBUTION
        env:
          CHANNEL: ${{ matrix.channel }}
          DISTRIBUTION: ${{ matrix.distribution }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-packages-${{ matrix.channel }}-${{ matrix.distribution }}
          path: |
            build/*.deb
