name: Build Release

on:
  workflow_dispatch:
    inputs:
      ice_version:
        description: "Version to build for all packages"
        required: true
        default: "3.8.0-alpha.0"

jobs:
  build-deb-packages:
    name: Build DEB Packages
    uses: ./.github/workflows/build-deb-packages.yml
    with:
      ice_version: ${{ github.event.inputs.ice_version }}

  build-dotnet-packages:
    name: Build .NET Packages
    uses: ./.github/workflows/build-dotnet-packages.yml
    with:
      ice_version: ${{ github.event.inputs.ice_version }}

  build-gem-packages:
    name: Build GEM Packages
    uses: ./.github/workflows/build-gem-packages.yml
    with:
      ice_version: ${{ github.event.inputs.ice_version }}

  build-matlab-packages:
    name: Build MATLAB Packages
    uses: ./.github/workflows/build-matlab-packages.yml
    with:
      ice_version: ${{ github.event.inputs.ice_version }}

  build-msi-package:
    name: Build MSI Package
    uses: ./.github/workflows/build-msi-package.yml
    with:
      ice_version: ${{ github.event.inputs.ice_version }}

  build-npm-packages:
    name: Build NPM Packages
    uses: ./.github/workflows/build-npm-packages.yml
    with:
      ice_version: ${{ github.event.inputs.ice_version }}

  build-pip-packages:
    name: Build PIP Packages
    uses: ./.github/workflows/build-pip-packages.yml
    with:
      ice_version: ${{ github.event.inputs.ice_version }}

  build-rpm-packages:
    name: Build RPM Packages
    uses: ./.github/workflows/build-rpm-packages.yml
    with:
      ice_version: ${{ github.event.inputs.ice_version }}

  build-xcframework-packages:
    name: Build XCFramework Packages
    uses: ./.github/workflows/build-xcframework-packages.yml
    with:
      ice_version: ${{ github.event.inputs.ice_version }}
