name: "Build GEM Packages"

on:
  workflow_call:
    inputs:
      ice_version:
        required: true
        type: string
      repository_url:
        required: true
        type: string
    secrets:
      RUBYGEMS_API_KEY:
        required: false
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version to build"
        required: false
      repository_url:
        description: "The URL of the GEM repository to publish to"
        required: false
        type: string

jobs:
  build-python-packages:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Install Build Dependencies
        run: gem install rake

      - name: Update GEM Version
        working-directory: ruby
        run: sed -i "s/spec.version.*/spec.version = '${{ inputs.ice_version }}'/" ice.gemspec
        if: inputs.ice_version != ''

      - name: Build GEM Package
        working-directory: ruby
        run: rake

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gem-packages
          path: ruby/*.gem

      - name: Publish GEM Packages
        run: |
          gem push ruby/*.gem --host ${{ inputs.repository_url }}
        if: inputs.repository_url != ''
