name: "Build MATLAB Packages"

on:
  workflow_call: # Allows calling from other workflows
  workflow_dispatch: # Allows manual triggering

jobs:
  build-python-packages:

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          use_matlab: true

      - name: Build MATLAB ToolBox
        run: make -C matlab toolbox
        if: runner.os == 'Linux'

      - name: Build MATLAB ToolBox
        run: MSBuild /p:Configuration=Release /p:Platform=x64 /t:Package matlab\msbuild\ice.proj
        if: runner.os == 'Windows'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: matlab-packages-${{ matrix.os }}
          path: matlab/toolbox/*.mltbx
