name: "Build RPM Packages"

on:
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version to build"
        required: false
      repository_url:
        description: "The URL of the Nexus repository to publish to"
        required: false
        type: string
      repository_suffix:
        description: "The suffix to append to the repository URL"
        required: false
        type: string
  workflow_call:
    inputs:
      ice_version:
        required: false
        type: string
      repository_url:
        required: false
        type: string
      repository_suffix:
        required: false
        type: string
    secrets:
      REPOSITORY_USERNAME:
        required: false
      REPOSITORY_PASSWORD:
        required: false

jobs:
  build:
    name: "Build for ${{ matrix.distribution }}-${{ matrix.arch }}"
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        include:
          - distribution: rhel9
            arch: x86_64

          - distribution: rhel9
            arch: i686

          - distribution: rhel9
            arch: aarch64

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: ice

      - name: Call Build RPM Package Action
        uses: ./ice/.github/actions/build-rpm-package
        with:
          ice_version: ${{ inputs.ice_version || '' }}
          distribution: ${{ matrix.distribution }}
          arch: ${{ matrix.arch }}
          repository_url: ${{ inputs.repository_url || ''}}
          repository_suffix: ${{ inputs.repository_suffix || '' }}
        env:
          REPOSITORY_USERNAME: ${{ secrets.REPOSITORY_USERNAME }}
          REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
