name: "Build MSI Package"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-msi-package:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      # TODO Download from NuGet
      - name: Build C++ Binaries
        run: msbuild /m ice.proj /p:Platform=x64 /p:Configuration=Release
        working-directory: cpp/msbuild

      - name: Build IceGrid GUI
        run: ./gradlew.bat dist -PcppPlatform=x64 -PcppConfiguration=Release
        working-directory: java

      - name: Build MSI
        run: dotnet build -c Release -p:Platform=x64
        working-directory: packaging/msi
        env:
          # TODO compute this variable see issue #3558
          VCInstallDir: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC"

      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi
          path: |
            packaging/msi/bin/x64/Release/*.msi
