name: ci

on:
  workflow_dispatch:
  push:
    branches: ["3.7", "main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["3.7", "main"]
  schedule:
    - cron: "34 18 * * 3"

jobs:
  build-and-test:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        run: make -j8 V=1 CONFIGS="shared cpp98-shared cpp11-shared"
      - name: Test
        run: ./allTests.py --workers=4
